name: Deployment testing
on:
  push:
    branches:
      - main
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  linter-formatter:
    name: Run linter and formatteur
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run linter 
        run: npm run lint 

      - name: Run format
        run: npm run format

      - name: Run test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Run End-To-End Test
        run: npm run test:e2e:dev
