name: Deployment testing
on:
  push:
    branches:
      - main
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  cypress-run:
  runs-on: ubuntu-22.04
  container:
    image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
    options: --user 1001
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Start Server and Test
      uses: cypress-io/github-action@v6
      with:
        start: npm run test:e2e:dev
        wait-on: 'http://localhost:3000'
        wait-on-timeout: 60
        browser: chrome

  lint:
    name: Run linter and formatteur
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run linter 
        run: npm run lint 
      
      - name: Run format
        run: npm run format
  
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run test
        run: npm run test

  build:  
    name: Run build and e2e test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

       
          